#!/usr/bin/env bash
#install Nginx
sudo apt-get -y update
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
sudo sed -i 's/^\(.*listen .*:\).*$/\180;/' /etc/nginx/sites-available/default
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo service nginc start
