#!/usr/bin/env bash
# redirect to another page
sudo apt-get update
sudo apt-get install -y nginx
#mkdir /etc/nginx/html
#touch /etc/nginx/html/index.html
echo "Hello World!" | sudo tee /etc/nginx/html/index.html
sudo bash -c 'cat <<EOL > /etc/nginx/sites-available/redirect_me
server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Additional Configuration (if any)
}
EOL'
#sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/
sudo rm -f /etc/nginx/sites-enabled/default

sudo service nginx restart

