#!/usr/bin/env bash
# redirect to another web page
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i '26\
	rewrite ^/redirect_me https://www.youtube.com/watch?v=bfrP4MEXawA permanent;' /etc/nginx/sites-enabled/default
sudo service nginx start

