#!/usr/bin/env bash
# redirect to another page
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i "24i\ rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx start
