#!/usr/bin/env bash
# Script that symbo linkes the sites-enabled and sites-available folders
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
